"""add new modules

Revision ID: 0b220c475d23
Revises: 3548d7028c37
Create Date: 2026-07-28 02:33:22.023183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b220c475d23'
down_revision = '3548d7028c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_blocks',
    sa.Column('page', sa.String(length=50), nullable=False),
    sa.Column('section_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page', 'section_key', name='uq_content_block_page_section')
    )
    with op.batch_alter_table('content_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_blocks_page'), ['page'], unique=False)

    op.create_table('seo_settings',
    sa.Column('default_meta_title', sa.String(length=255), nullable=False),
    sa.Column('default_meta_description', sa.String(length=500), nullable=True),
    sa.Column('default_og_image_url', sa.String(length=500), nullable=True),
    sa.Column('google_analytics_id', sa.String(length=100), nullable=True),
    sa.Column('google_site_verification', sa.String(length=255), nullable=True),
    sa.Column('robots_txt', sa.Text(), nullable=True),
    sa.Column('sitemap_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('area_of_interest', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='volunteer_status'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteers_status'), ['status'], unique=False)

    op.create_table('website_settings',
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_files',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_files_uploaded_by_id'), ['uploaded_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_files_uploaded_by_id'))

    op.drop_table('media_files')
    op.drop_table('website_settings')
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteers_status'))

    op.drop_table('volunteers')
    op.drop_table('team_members')
    op.drop_table('seo_settings')
    with op.batch_alter_table('content_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_blocks_page'))

    op.drop_table('content_blocks')
    # ### end Alembic commands ###
