"""add payment screenshot and donation settings fields

Revision ID: 896ffae34d7b
Revises: 0b220c475d23
Create Date: 2026-08-01 20:34:59.803379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896ffae34d7b'
down_revision = '0b220c475d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_screenshot_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('website_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_bank_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('donation_account_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('donation_account_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('donation_iban', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('donation_swift_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('donation_jazzcash_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('donation_easypaisa_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('donation_raast_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('donation_instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website_settings', schema=None) as batch_op:
        batch_op.drop_column('donation_instructions')
        batch_op.drop_column('donation_raast_id')
        batch_op.drop_column('donation_easypaisa_number')
        batch_op.drop_column('donation_jazzcash_number')
        batch_op.drop_column('donation_swift_code')
        batch_op.drop_column('donation_iban')
        batch_op.drop_column('donation_account_number')
        batch_op.drop_column('donation_account_title')
        batch_op.drop_column('donation_bank_name')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('payment_screenshot_url')

    # ### end Alembic commands ###
