"""add google_tag_manager_id to seo_settings

Revision ID: 8b502304a953
Revises: aae77d6d7b5a
Create Date: 2026-08-15 17:41:16.024794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b502304a953'
down_revision = 'aae77d6d7b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seo_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_tag_manager_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seo_settings', schema=None) as batch_op:
        batch_op.drop_column('google_tag_manager_id')

    # ### end Alembic commands ###
