"""add page_views table

Revision ID: aae77d6d7b5a
Revises: 896ffae34d7b
Create Date: 2026-08-15 16:35:38.717765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae77d6d7b5a'
down_revision = '896ffae34d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_views',
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_views_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_views_visitor_hash'), ['visitor_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_views_visitor_hash'))
        batch_op.drop_index(batch_op.f('ix_page_views_path'))

    op.drop_table('page_views')
    # ### end Alembic commands ###
